### ISSUE TITLE
Pusher 2-hour synchronization

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/pusher#71]
The new pusher dashboard reveals a stark 2-hour cycle for uploads. Evidently this is caused by the unintended synchronization at UTC 00:00 when the 2-hour timeout starts over.

![pusher-sync](https://user-images.githubusercontent.com/1085316/69271645-38dffe80-0ba3-11ea-8e50-b107243dc44d.png)

**Comment by pboothe** [comment]
To be more specific: this is caused by the 2 hour timeout being activated for the new directory that is created usually not very long after midnight.  The synchronization signal is the directory creation after the date change.  That complicates the fix, and means that we should add good randomization throughout instead of trying to solve this pattern in a piecewise manner..

**Comment by pboothe** [comment]
Fixed
